# docker-composeのバージョン
version: '3'
# アプリケーションを動かすための要素 web db　の各要素がある
services:
  db:
    # コンテナ作成に必要なイメージを指定 
    image: postgres:11.5
    # 環境変数
    environment:
        POSTGRES_USER: 'admin'
        POSTGRES_PASSWORD: 'admin-pass'
    # 各serviceのポート番号 ホストOS(local)のポート番号:dockerコンテナ内のポート番号
    ports:
      - "3306:3306"

  web:
    # docker-compose buildのときにビルドするためのDockerfileのパス
    build: .
    # docker-compose upで実行されるコマンド
    command: rails s -p 3000 -b '0.0.0.0'
    # dockerの中でデータを永続化する設定 コンテナ内のデータが消えずに残る
    volumes:
      - .:/cocktailSearchApp
    ports:
      - "3000:3000"
    links:
      - db 