# docker-composeのバージョン
version: '3'

services:
  db:
    # コンテナ作成に必要なイメージを指定 
    image: postgres:11.5
    # 環境変数
    environment:
        POSTGRES_USER: 'admin'
        POSTGRES_PASSWORD: 'admin-pass'
    ports:
      - "3306:3306"

  web:
    # buildのDockerfileのパス
    build: .
    # docker-compose upで実行されるコマンド
    #command: rails s -p 3000 -b '0.0.0.0'
    # webサーバー用のスクリプトを実行
    command: sh scripts/launch.sh
    volumes:
      - .:/cocktailSearchApp
      - public-data:/cocktailSearchApp/public
      - tmp-data:/cocktailSearchApp/tmp
      - log-data:/cocktailSearchApp/log
    ports:
      - "3000:3000"
    links:
      - db 

  nginx:
    # docker-compose buildのときにビルドするためのDockerfileのパス
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - public-data:/cocktailSearchApp/public
      - tmp-data:/cocktailSearchApp/tmp
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  public-data:
  tmp-data:
  log-data: