version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: docker-compose stop
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: bundle install
          command:  docker-compose run web bin/bundle install
      - run:
          name: test
          command: docker-compose run web bundle exec rspec ./spec/system/cocktails_spec.rb
      - run:
          name: docker-compose down
          command: docker-compose down
